eureka:
  client:
    service-url:
      defaultZone: http://sinfonia.top:20089/eureka/
demoservice:
  ribbon:
    listOfServers: http://sinfonia.top:10089,http://sinfonia.top:20089
ribbon:
  eureka:
    enabled: false